/* Rounds bedside tools — small calculators with live results. Tools.list, Tools.render(id, container). */
(function () {
  const h = (html) => { const t = document.createElement('template'); t.innerHTML = html.trim(); return t.content.firstElementChild; };
  const num = (el) => { const v = parseFloat(String(el.value).replace(',', '.')); return Number.isFinite(v) ? v : NaN; };
  const f = (v, d = 1) => (Number.isFinite(v) ? (Math.round(v * 10 ** d) / 10 ** d).toString() : '--');
  const field = (id, label, opts = {}) => `<div class="field"><label for="${id}">${label}</label><input id="${id}" type="text" inputmode="decimal" autocomplete="off" placeholder="${opts.ph || ''}" value="${opts.val ?? ''}"></div>`;
  const sel = (id, label, options, val) => `<div class="field"><label for="${id}">${label}</label><select id="${id}">${options.map((o) => `<option value="${o[0]}" ${String(o[0]) === String(val) ? 'selected' : ''}>${o[1]}</option>`).join('')}</select></div>`;
  const out = (rows) => `<div class="tool-out">${rows.map(([k, v, note]) => `<div class="tool-row"><span>${k}</span><b class="num">${v}</b>${note ? `<small>${note}</small>` : ''}</div>`).join('')}</div>`;

  const TOOLS = {
    convert: { title: 'Unit converter', sub: 'Pounds, kilograms, Fahrenheit, Celsius, inches, centimeters', form: () => `<div class="tool-grid">${field('lb', 'Pounds (lb)', { ph: '170' })}${field('kg', 'Kilograms (kg)', { ph: '77' })}${field('tf', 'Temp (°F)', { ph: '100.4' })}${field('tc', 'Temp (°C)', { ph: '38' })}${field('inch', 'Inches (in)', { ph: '70' })}${field('cm', 'Centimeters (cm)', { ph: '178' })}</div><p class="faint small">Type in any box and the partner updates. kg = lb ÷ 2.2. °C = (°F − 32) × 5/9.</p>`,
      wire: (el) => { const pair = (a, b, fab, fba) => { const A = el.querySelector('#' + a), B = el.querySelector('#' + b); A.addEventListener('input', () => { const v = num(A); B.value = Number.isFinite(v) ? f(fab(v), 1) : ''; }); B.addEventListener('input', () => { const v = num(B); A.value = Number.isFinite(v) ? f(fba(v), 1) : ''; }); }; pair('lb', 'kg', (v) => v / 2.2046, (v) => v * 2.2046); pair('tf', 'tc', (v) => (v - 32) * 5 / 9, (v) => v * 9 / 5 + 32); pair('inch', 'cm', (v) => v * 2.54, (v) => v / 2.54); } },
    dose: { title: 'Dose calculator', sub: 'Weight-based dose, then volume from concentration', form: () => `<div class="tool-grid">${field('w', 'Weight (kg)', { ph: '70' })}${field('dpk', 'Ordered dose (mg/kg)', { ph: '0.01' })}${field('d', 'Or flat dose (mg)', { ph: '' })}${field('conc', 'Concentration (mg/mL)', { ph: '1' })}</div><div id="r"></div><p class="faint small">Volume (mL) = dose (mg) ÷ concentration (mg/mL). Epinephrine 1 mg/mL is 1:1,000; 0.1 mg/mL is 1:10,000.</p>`,
      wire: (el) => { const upd = () => { const w = num(el.querySelector('#w')), dpk = num(el.querySelector('#dpk')), flat = num(el.querySelector('#d')), c = num(el.querySelector('#conc')); const dose = Number.isFinite(flat) && el.querySelector('#d').value ? flat : w * dpk; el.querySelector('#r').innerHTML = out([['Dose', f(dose, 3) + ' mg'], ['Volume', f(dose / c, 2) + ' mL', Number.isFinite(c) ? 'at ' + c + ' mg/mL' : '']]); }; el.querySelectorAll('input').forEach((i) => i.addEventListener('input', upd)); upd(); } },
    drip: { title: 'IV rate', sub: 'mL/h and drops per minute', form: () => `<div class="tool-grid">${field('vol', 'Volume (mL)', { ph: '1000' })}${field('min', 'Over (minutes)', { ph: '480' })}${sel('df', 'Drop factor (gtt/mL)', [[10, '10 (macro)'], [15, '15 (macro)'], [20, '20 (macro)'], [60, '60 (micro)']], 15)}</div><div id="r"></div><p class="faint small">gtt/min = volume × drop factor ÷ minutes. Maintenance 4-2-1: 4 mL/kg/h for the first 10 kg, 2 for the next 10, 1 for the rest.</p>`,
      wire: (el) => { const upd = () => { const v = num(el.querySelector('#vol')), m = num(el.querySelector('#min')), df = +el.querySelector('#df').value; el.querySelector('#r').innerHTML = out([['Rate', f(v / m * 60, 0) + ' mL/h'], ['Drip', f(v * df / m, 0) + ' gtt/min']]); }; el.querySelectorAll('input,select').forEach((i) => i.addEventListener('input', upd)); upd(); } },
    o2: { title: 'Oxygen cylinder duration', sub: 'How long a tank lasts at a flow rate', form: () => `<div class="tool-grid">${sel('cyl', 'Cylinder', [[0.16, 'D (0.16)'], [0.28, 'E (0.28)'], [1.56, 'M (1.56)'], [3.14, 'H/K (3.14)']], 0.28)}${field('psi', 'Gauge (psi)', { ph: '2000' })}${field('flow', 'Flow (L/min)', { ph: '15' })}${field('res', 'Safe residual (psi)', { val: 200 })}</div><div id="r"></div><p class="faint small">Minutes = (psi − residual) × constant ÷ flow.</p>`,
      wire: (el) => { const upd = () => { const k = +el.querySelector('#cyl').value, p = num(el.querySelector('#psi')), fl = num(el.querySelector('#flow')), r = num(el.querySelector('#res')) || 0; const min = (p - r) * k / fl; el.querySelector('#r').innerHTML = out([['Duration', f(min, 0) + ' min', Number.isFinite(min) ? Math.floor(min / 60) + ' h ' + Math.round(min % 60) + ' min' : '']]); }; el.querySelectorAll('input,select').forEach((i) => i.addEventListener('input', upd)); upd(); } },
    perfusion: { title: 'MAP, pulse pressure, shock index', sub: 'From a blood pressure and heart rate', form: () => `<div class="tool-grid">${field('sbp', 'Systolic', { ph: '110' })}${field('dbp', 'Diastolic', { ph: '70' })}${field('hr', 'Heart rate', { ph: '96' })}</div><div id="r"></div><p class="faint small">MAP = (SBP + 2 × DBP) ÷ 3; 65 is the perfusion floor. Shock index = HR ÷ SBP; above 0.9 is concerning, above 1.0 is shock until proven otherwise.</p>`,
      wire: (el) => { const upd = () => { const s = num(el.querySelector('#sbp')), d = num(el.querySelector('#dbp')), hr = num(el.querySelector('#hr')); const map = (s + 2 * d) / 3, si = hr / s; el.querySelector('#r').innerHTML = out([['MAP', f(map, 0), Number.isFinite(map) ? (map < 65 ? 'below the 65 floor' : 'adequate') : ''], ['Pulse pressure', f(s - d, 0), Number.isFinite(s - d) ? (s - d < 25 ? 'narrow' : s - d > 60 ? 'wide' : 'normal') : ''], ['Shock index', f(si, 2), Number.isFinite(si) ? (si > 1 ? 'shock range' : si > 0.9 ? 'concerning' : 'normal') : '']]); }; el.querySelectorAll('input').forEach((i) => i.addEventListener('input', upd)); upd(); } },
    gcs: { title: 'Glasgow Coma Scale', sub: 'Eyes, verbal, motor', form: () => `<div class="tool-grid">${sel('e', 'Eyes', [[4, '4 Spontaneous'], [3, '3 To voice'], [2, '2 To pain'], [1, '1 None']], 4)}${sel('v', 'Verbal', [[5, '5 Oriented'], [4, '4 Confused'], [3, '3 Inappropriate words'], [2, '2 Incomprehensible sounds'], [1, '1 None']], 5)}${sel('m', 'Motor', [[6, '6 Obeys commands'], [5, '5 Localizes pain'], [4, '4 Withdraws from pain'], [3, '3 Abnormal flexion (decorticate)'], [2, '2 Extension (decerebrate)'], [1, '1 None']], 6)}</div><div id="r"></div><p class="faint small">13–15 mild, 9–12 moderate, 3–8 severe. GCS 8 or less: think airway.</p>`,
      wire: (el) => { const upd = () => { const e = +el.querySelector('#e').value, v = +el.querySelector('#v').value, m = +el.querySelector('#m').value; const t = e + v + m; el.querySelector('#r').innerHTML = out([['GCS', t + ' (E' + e + ' V' + v + ' M' + m + ')', t >= 13 ? 'mild' : t >= 9 ? 'moderate' : 'severe']]); }; el.querySelectorAll('select').forEach((i) => i.addEventListener('input', upd)); upd(); } },
    apgar: { title: 'APGAR', sub: 'Score at 1 and 5 minutes', form: () => `<div class="tool-grid">${sel('a', 'Appearance', [[2, '2 Pink'], [1, '1 Blue extremities'], [0, '0 Blue/pale']], 2)}${sel('p', 'Pulse', [[2, '2 Over 100'], [1, '1 Under 100'], [0, '0 Absent']], 2)}${sel('g', 'Grimace', [[2, '2 Cries/pulls away'], [1, '1 Grimace'], [0, '0 No response']], 2)}${sel('ac', 'Activity', [[2, '2 Active motion'], [1, '1 Some flexion'], [0, '0 Limp']], 2)}${sel('r', 'Respirations', [[2, '2 Strong cry'], [1, '1 Slow/irregular'], [0, '0 Absent']], 2)}</div><div id="r"></div><p class="faint small">7–10 normal, 4–6 needs support, 0–3 resuscitate. Do not delay resuscitation to score.</p>`,
      wire: (el) => { const upd = () => { const t = ['a', 'p', 'g', 'ac', 'r'].reduce((s, k) => s + +el.querySelector('#' + k).value, 0); el.querySelector('#r').innerHTML = out([['APGAR', String(t), t >= 7 ? 'normal' : t >= 4 ? 'needs support' : 'resuscitate']]); }; el.querySelectorAll('select').forEach((i) => i.addEventListener('input', upd)); upd(); } },
    burns: { title: 'Burn size and Parkland', sub: 'Rule of nines and the first 24 hours of fluid', form: () => `<div class="field"><label>Adult regions burned (partial or full thickness)</label><div class="opt-grid" id="regions">${[['Head', 9], ['Front torso', 18], ['Back torso', 18], ['Right arm', 9], ['Left arm', 9], ['Right leg', 18], ['Left leg', 18], ['Groin', 1]].map(([n, p]) => `<button class="opt" data-p="${p}">${n}<small>${p}%</small></button>`).join('')}</div></div><div class="tool-grid">${field('extra', 'Plus palm-method patches (%)', { ph: '0' })}${field('w', 'Weight (kg)', { ph: '70' })}</div><div id="r"></div><p class="faint small">Parkland: 4 mL × kg × %TBSA of lactated Ringer's over 24 h, half in the first 8 h from the time of the burn. Adult figures; children use a modified chart.</p>`,
      wire: (el) => { const upd = () => { let pct = 0; el.querySelectorAll('#regions .opt.on').forEach((b) => pct += +b.dataset.p); pct += num(el.querySelector('#extra')) || 0; const w = num(el.querySelector('#w')); const total = 4 * w * pct; el.querySelector('#r').innerHTML = out([['TBSA', pct + '%', pct >= 20 ? 'major burn' : pct >= 10 ? 'significant' : ''], ['24-hour fluid', f(total, 0) + ' mL'], ['First 8 hours', f(total / 2, 0) + ' mL', Number.isFinite(total) ? f(total / 2 / 8, 0) + ' mL/h' : '']]); }; el.querySelectorAll('#regions .opt').forEach((b) => b.onclick = () => { b.classList.toggle('on'); upd(); }); el.querySelectorAll('input').forEach((i) => i.addEventListener('input', upd)); upd(); } },
    peds: { title: 'Pediatric estimates', sub: 'Weight, lowest acceptable blood pressure, tube size from age', form: () => `<div class="tool-grid">${field('age', 'Age (years)', { ph: '4' })}</div><div id="r"></div><p class="faint small">Weight ≈ (age × 2) + 8 kg for ages 1–10. Minimum systolic ≈ 70 + 2 × age (ages 1–10). Uncuffed ETT ≈ (age ÷ 4) + 4. A length-based tape beats every formula.</p>`,
      wire: (el) => { const upd = () => { const a = num(el.querySelector('#age')); el.querySelector('#r').innerHTML = out([['Estimated weight', f(a * 2 + 8, 0) + ' kg'], ['Minimum SBP', f(70 + 2 * a, 0) + ' mmHg'], ['Uncuffed ETT', f(a / 4 + 4, 1) + ' mm', 'cuffed: subtract 0.5'], ['20 mL/kg bolus', f((a * 2 + 8) * 20, 0) + ' mL']]); }; el.querySelectorAll('input').forEach((i) => i.addEventListener('input', upd)); upd(); } },
    qtc: { title: 'QTc', sub: 'Corrected QT by Bazett', form: () => `<div class="tool-grid">${field('qt', 'QT (ms)', { ph: '400' })}${field('hr', 'Heart rate', { ph: '80' })}</div><div id="r"></div><p class="faint small">QTc = QT ÷ √RR (RR in seconds). Prolonged above 450 ms (men) / 470 ms (women); 500 ms is the danger line.</p>`,
      wire: (el) => { const upd = () => { const qt = num(el.querySelector('#qt')), hr = num(el.querySelector('#hr')); const rr = 60 / hr; const qtc = qt / Math.sqrt(rr); el.querySelector('#r').innerHTML = out([['QTc', f(qtc, 0) + ' ms', Number.isFinite(qtc) ? (qtc >= 500 ? 'dangerous' : qtc > 470 ? 'prolonged' : qtc > 450 ? 'borderline (men prolonged)' : 'normal') : '']]); }; el.querySelectorAll('input').forEach((i) => i.addEventListener('input', upd)); upd(); } },
    chem: { title: 'Anion gap and corrected calcium', sub: 'From a basic metabolic panel', form: () => `<div class="tool-grid">${field('na', 'Sodium', { ph: '140' })}${field('cl', 'Chloride', { ph: '104' })}${field('hco3', 'Bicarbonate (CO2)', { ph: '24' })}${field('ca', 'Calcium', { ph: '9.0' })}${field('alb', 'Albumin (g/dL)', { ph: '4.0' })}</div><div id="r"></div><p class="faint small">Gap = Na − (Cl + HCO3), normal 8–12. Corrected Ca = Ca + 0.8 × (4 − albumin).</p>`,
      wire: (el) => { const upd = () => { const na = num(el.querySelector('#na')), cl = num(el.querySelector('#cl')), b = num(el.querySelector('#hco3')), ca = num(el.querySelector('#ca')), al = num(el.querySelector('#alb')); const gap = na - (cl + b); el.querySelector('#r').innerHTML = out([['Anion gap', f(gap, 0), Number.isFinite(gap) ? (gap > 12 ? 'elevated: think MUDPILES' : 'normal') : ''], ['Corrected calcium', f(ca + 0.8 * (4 - al), 1)]]); }; el.querySelectorAll('input').forEach((i) => i.addEventListener('input', upd)); upd(); } },
    bmi: { title: 'BMI and ideal body weight', sub: 'From height and weight', form: () => `<div class="tool-grid">${field('ht', 'Height (in)', { ph: '70' })}${field('wt', 'Weight (lb)', { ph: '190' })}${sel('sex', 'Sex', [['m', 'Male'], ['f', 'Female']], 'm')}</div><div id="r"></div><p class="faint small">IBW (Devine): men 50 kg + 2.3 kg per inch over 60; women 45.5 kg + 2.3 per inch over 60. Some drugs dose on IBW.</p>`,
      wire: (el) => { const upd = () => { const ht = num(el.querySelector('#ht')), wt = num(el.querySelector('#wt')), sex = el.querySelector('#sex').value; const kg = wt / 2.2046, m = ht * 0.0254; const bmi = kg / (m * m); const ibw = (sex === 'm' ? 50 : 45.5) + 2.3 * (ht - 60); el.querySelector('#r').innerHTML = out([['BMI', f(bmi, 1), Number.isFinite(bmi) ? (bmi >= 30 ? 'obese' : bmi >= 25 ? 'overweight' : bmi >= 18.5 ? 'normal' : 'underweight') : ''], ['Ideal body weight', f(ibw, 0) + ' kg']]); }; el.querySelectorAll('input,select').forEach((i) => i.addEventListener('input', upd)); upd(); } },
    rate: { title: 'ECG rate from boxes', sub: 'Big boxes or small boxes between R waves', form: () => `<div class="tool-grid">${field('big', 'Big boxes between R waves', { ph: '4' })}${field('small', 'Or small boxes', { ph: '' })}${field('six', 'Or complexes in 6 seconds', { ph: '' })}</div><div id="r"></div><p class="faint small">300 ÷ big boxes. 1500 ÷ small boxes. Complexes in 6 s × 10 for irregular rhythms.</p>`,
      wire: (el) => { const upd = () => { const b = num(el.querySelector('#big')), s = num(el.querySelector('#small')), six = num(el.querySelector('#six')); el.querySelector('#r').innerHTML = out([['From big boxes', f(300 / b, 0) + ' /min'], ['From small boxes', f(1500 / s, 0) + ' /min'], ['From 6-second strip', f(six * 10, 0) + ' /min']]); }; el.querySelectorAll('input').forEach((i) => i.addEventListener('input', upd)); upd(); } },
  };
  window.Tools = {
    list: Object.entries(TOOLS).map(([id, t]) => ({ id, title: t.title, sub: t.sub })),
    render(id, container) { const t = TOOLS[id]; if (!t) return; const el = h(`<div class="tool"><div class="eyebrow accent">Tool</div><h2 style="margin-top:6px">${t.title}</h2><p class="muted small" style="margin:4px 0 14px">${t.sub}</p>${t.form()}</div>`); container.appendChild(el); t.wire(el); },
  };
})();
